name: spend_wise
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.13
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_iconly: ^1.0.2
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.2.8
  google_nav_bar: ^5.0.6
  iconly: ^1.0.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  jwt_decoder: ^2.0.1
  line_icons: ^2.0.3
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
  class_name: Localizely
